; empty config to fix `spicetify apply` error ouput

[turntable]
[mocha]
text               = ede3ea
subtext            = bca9b6
main               = 1e1e2e
main-elevated      = 181825
highlight          = 313244
highlight-elevated = 45475a
sidebar            = 181825
player             = 181825
card               = 313244
shadow             = 11111b
selected-row       = bca9b6
button             = bc8ead
button-active      = bc8ead
button-disabled    = 585b70
tab-active         = 313244
notification       = 313244
notification-error = f38ba8
misc               = 766070
